generatorName: scala-tapir
outputDir: samples/client/petstore/scala-tapir
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-tapir
additionalProperties:
  artifactId: scala-tapir-petstore
  circe: true