/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.core

import org.openapitools.client.model._

import io.circe.Codec
import io.circe.generic.AutoDerivation
import sttp.tapir.json.circe.TapirJsonCirce
import sttp.tapir.Schema
import sttp.tapir.SchemaType.SString

object JsonSupport extends AutoDerivation with DateSerializers with TapirJsonCirce {
  implicit def schemEnumeration[T <: Enumeration#Value]: Schema[T] = Schema(SString())

  implicit val OrderStatusDecoder: Codec[OrderEnums.Status] = Codec.codecForEnumeration(OrderEnums.Status)

  implicit val PetStatusDecoder: Codec[PetEnums.Status] = Codec.codecForEnumeration(PetEnums.Status)

}
